FROM fedora:43

RUN echo -e '[main]\nmax_parallel_downloads=10\nfastestmirror=True' >> /etc/dnf/dnf.conf

# frantisekz/GNOME-X11 COPR provides GNOME 49 X11 session support on Fedora 43
RUN dnf -y copr enable frantisekz/GNOME-X11 && dnf -y update && \
    dnf -y install \
        gnome-shell \
        gjs \
        xorg-x11-server-Xvfb \
        dbus \
        dbus-x11 \
        mesa-dri-drivers \
        mesa-libGL \
        unzip \
        ImageMagick \
        xwininfo \
        pipewire \
        wireplumber \
        pipewire-gstreamer \
        gstreamer1 \
        gstreamer1-plugins-base \
        gstreamer1-plugins-good \
        && \
    dnf clean all

RUN useradd -ms /bin/bash tester && \
    mkdir -p /tmp/runtime-tester /tmp/.X11-unix && \
    chown tester:tester /tmp/runtime-tester && \
    chmod 700 /tmp/runtime-tester && \
    chmod 1777 /tmp/.X11-unix

COPY run-test.sh /run-test.sh
COPY fake-logind.js /fake-logind.js
COPY grab-frame.js /grab-frame.js
RUN chmod +x /run-test.sh

USER tester
ENV HOME=/home/tester
ENV XDG_RUNTIME_DIR=/tmp/runtime-tester
ENV NO_AT_BRIDGE=1
WORKDIR /home/tester
